### PR TITLE
Added a keyboard shortcut to quit apps (CTRL+Q)

### PR DESCRIPTION
**Pull request by neue**
This keybinding will make it possible to quit apps using CTRL-Q. Very handy when testing things over and over.

### CODE REVIEW

**Comment by convolu** [comment]
:+1: :-)

Have you tested it?

**Comment by neue** [comment]
Tested it? I'm **living** the CTRL+Q dream over here.

File I had to change on my system was `~/.config/openbox/lxde-rc.xml` presumably that `rc.xml` becomes `lxde-rc.xml` during install?

**Comment by convolu** [comment]
@radujipa  @pazdera let's add it for Monday's image

**Comment by pazdera** [comment]
Oh, I completely missed this! Sorry about that.

Do we need to add it to the updater as well?

cc @alex5imon

**Comment by Ealdwulf** [comment]
@neue This PR is to the jessie branch, if you want it can you reopen agains master? (I'd do it except it's from your github account, so I can't)

**Pull request closed without merging**
