### PR TITLE
Adding openbox config for Kwebapp

### PR DESCRIPTION
**Pull request by pazdera**
This should be it, @rluz 

Related to: https://github.com/KanoComputing/peldins/issues/1794#issuecomment-99503769

cc @alex5imon

### CODE REVIEW

**Comment by tombettany** [comment]
@pazdera This looks valid.

**Comment by pazdera** [comment]
@rluz Feel free to merge this Richardo when you need it :-).

**Comment by rluz** [comment]
@pazdera can you please change ```Kwebapp``` to ```Midori```

**Comment by pazdera** [comment]
@rluz done!

**Comment by alex5imon** [comment]
@rluz I don't think this will be needed. We should have a python wrapper that embeds the Midori window instead

**Comment by pazdera** [comment]
Ok, closing this one then :-).

**Pull request closed without merging**
