### PR TITLE
Fix for some apps not displaying i18n messages correctly

### PR DESCRIPTION
**Pull request by skarbat**
This change fixes terminal quest messages eventually displaying garbage for non-ascii translated messages

### CODE REVIEW

**Comment by skarbat** [comment]
[TQ: word "tiles" in one of the scrolls](https://trello.com/c/0qidLAIi/117-tq-word-tiles-in-one-of-the-scrolls)

**Comment by skarbat** [comment]
[TQ: accents displaying as ?? in right hand panel](https://trello.com/c/6AkPLSuN/116-tq-accents-displaying-as-in-right-hand-panel)

**Comment by radujipa** [comment]
I couldn't actually reproduce that bug, but I can't see anything wrong with the var here. 👍

**Comment by skarbat** [comment]
Thanks @radujipa , I could actually reproduce on challenge 26, on second step with `cd nowhere` . Merging for testing tomorrow.

**Comment by radujipa** [comment]
[Terminal Quest: Items and objects (files and folders) within the app have English names.](https://trello.com/c/XAXRkBek/53-terminal-quest-items-and-objects-files-and-folders-within-the-app-have-english-names)

**Pull request merged**
