### PR TITLE
I18n prep

### PR DESCRIPTION
**Pull request by Ealdwulf**
@tombettany Keith left this in a branch, maybe it fixes make-art?
We should either take it or close it.

### CODE REVIEW

**Comment by tombettany** [comment]
Hmm, this looks like we might need this - I have no idea if it works but it looks promising.

**Comment by skarbat** [comment]
I just tested that one on the PI es_AR and I still see messages in English.

**Comment by skarbat** [comment]
I'm sure it has to be easy but I can't make it work with this PR changes.
If I finally add the language interactively to Chromium, I correctly get this upstream: 
`Accept-Language: en-US,en;q=0.8,es;q=0.6` .

However, both make art desktop app and web url are still in english :-(

**Comment by Ealdwulf** [comment]
Alosing to reopen against master.

**Pull request closed without merging**
