### PR TITLE
Enabling the power button at bootup after daemons start

### PR DESCRIPTION
**Pull request by radujipa**
@skarbat @tombettany

### CODE REVIEW

**Comment by radujipa** [comment]
[(2) There is no restriction on when the shutdown menu pops up by pressing the power button on the PiHat](https://trello.com/c/nAQEjY0F/871-2-there-is-no-restriction-on-when-the-shutdown-menu-pops-up-by-pressing-the-power-button-on-the-pihat)

**Comment by skarbat** [comment]
This surely runs fine as a regular user? Thinking on I/O access to the ports.
Otherwise looks good @radujipa

**Comment by radujipa** [comment]
I'll hold off from merging until the lib is fixed so I can test this. However, the script itself should be allowed to run just fine given that it's calling the methods via DBus and it's not doing any actual heavy lifting itself.

**Comment by skarbat** [comment]
Oh, my bad Radu. Of course the other end of the dbus connection will run as whichever user needs to be. Should be fine me thinks

**Comment by radujipa** [comment]
Tested and it works :shipit:

**Pull request merged**
