### PR TITLE
Move Scratch and Video over by a place

### PR DESCRIPTION
**Pull request by convolu**
Make Light will be inserted in place 2 instead

work towards https://github.com/KanoComputing/peldins/issues/2162

Needs to be merged on the same day as https://github.com/KanoComputing/make-light/pull/203

### CODE REVIEW

**Comment by convolu** [comment]
@skarbat @pazdera @alex5imon Could you please review?

**Comment by skarbat** [comment]
Looks good to me @convolu , when you say 2, you mean third position to the naked eye right? (next to TQ) And the X below will be changed to a 2 I believe - pretty sure am missing a PR somewhere :)

 * https://github.com/KanoComputing/make-light/blob/jessie/kdesktop/Light.lnk#L10

**Comment by convolu** [comment]
@skarbat That is correct. I have made that change in make-light [here](https://github.com/KanoComputing/make-light/pull/203)

**Comment by pazdera** [comment]
:shipit:

**Comment by convolu** [comment]
Thanks, merging

**Pull request merged**
