### PR TITLE
Dashboard Mode: Ensure tracking sync on boot

### PR DESCRIPTION
**Pull request by tombettany**
Ensure that the tracking events are synced at boot. Also sync
kano-content and register a startup event.

@skarbat @Ealdwulf I included a couple of extra commands which seemed important in the dashboard init; let me know if they are unneeded.

### CODE REVIEW

**Comment by skarbat** [comment]
Looks ok to me @tombettany 

Just to make sure, these events are particular to every user, correct?
Because they will eventually be audited when users switch through the greeter.

**Comment by tombettany** [comment]
@Ealdwulf I know that this stuff doesn't merge but is it handled by https://github.com/KanoComputing/kano-desktop/pull/151 and friends or do we still need to do it?

**Comment by Ealdwulf** [comment]
@tombettany We won't end up with multiple trackers running. Might still want to only run the startup event once per boot - which could be done my moving it here: https://github.com/KanoComputing/kano-desktop/blob/jessie/bin/kano-uixinit#L74

**Comment by alex5imon** [comment]
@skarbat @tombettany what's the status of this branch?

**Comment by skarbat** [comment]
I think it's obsoleted and resolved elsewhere, but I am not sure where @alex5imon @tombettany

**Comment by tombettany** [comment]
@skarbat @Ealdwulf Made it mergable and adds the fix for the problem with first boot detection. I'll merge now for the image tomorrow - we can always revert if we are not pleased.

**Pull request merged**
