### PR TITLE
Fix sudo command.

### PR DESCRIPTION
**Pull request by Ealdwulf**
The use of WRAPPER didn't actually work, just calling sudo directly.

### CODE REVIEW

**Comment by Ealdwulf** [comment]
Merging to test.

**Comment by skarbat** [comment]
@Ealdwulf I get a password prompt if I `sudo scratch`.
Could that be the reason? We have this sudo rule:

 ```
# Allow the new version of scratch to be sudoed and preserve the environment
# This is because it now starts up inside a virtual machine
%sudo   ALL=NOPASSWD:SETENV: /usr/bin/squeak
```

**Comment by Ealdwulf** [comment]
@skarbat You're right, we need to change that to scratch; I'll do it.

**Comment by alex5imon** [comment]
Do we need to add a post update rule as well to fix this problem for users updating?

**Comment by Ealdwulf** [comment]
@alex5imon I think this line should already do it: https://github.com/KanoComputing/kano-desktop/blob/jessie/debian/postinst#L98

**Comment by alex5imon** [comment]
cool, just double checking. Thanks @Ealdwulf

**Pull request merged**
